cluster:
  nodes:
    - id: 0
      address: localhost
      rpcPort: 5000
      kvPort: 5001
    - id: 1
      address: localhost
      rpcPort: 5002
      kvPort: 5003
    - id: 2
      address: localhost
      rpcPort: 5004
      kvPort: 5005
  
  timeout:
    heartbeat: 5000
    electionTimeoutMin: 15000
    electionTimeoutMax: 30000